### ISSUE TITLE
Using with APC

### ISSUE THREAD

**Issue by paulm17** [danmontgomery/codeigniter-session-driver#2]
Keep on getting this error when using with APC.

2011/12/20 18:33:04 [error] 1198#0: *655 FastCGI sent in stderr: "PHP Warning:  include(application/errors/error_php.php): failed to open stream: No such file or directory in /srv/www/www.cidev.com/public_html/system/core/Exceptions.php on line 182
PHP Warning:  include(): Failed opening 'application/errors/error_php.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php') in /srv/www/www.cidev.com/public_html/system/core/Exceptions.php on line 182" while reading upstream, client: 192.168.1.7, server: www.cidev.com, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "www.cidev.com"
- If I use APC on it's own and not this driver, no issues.
- If I use APC and session driver Native in the config, no issues.
- Issues arise only when I use APC and session driver Cache in the config.

Would be good if you can duplicate and fix.  :)

Oh using the latest CI as well.

**Comment by paulm17** [comment]
When I give it the absolute path, I now get this error message.

Severity: Warning
Message: Cannot modify header information - headers already sent by (output started at /srv/www/www.cidev.com/public_html/system/core/Output.php:445)
Filename: session/Session_cache.php
Line Number: 293

Final observation, the error message occurs right at the bottom of the page.  It's like everything is rendered then at the end it tries to write the cookie...

Oh I get this error when using database, cookie, cache drivers.. Only works fine with native!

**Comment by paulm17** [comment]
Well, since Native sessions was working fine, I decided to use that in-conjunction with APC.

http://pastie.org/3049102

APC seems to show the initial session and when I log in the system the cached session gets updated.

The problem I have is that when I log out, the old session doesn't get deleted and a new one get written.

2011/12/20 21:23:18 [error] 1198#0: *2002 FastCGI sent in stderr: "session destroy: i6m8271cnlqpcs5hqg5hr5eqn2
session write: i6m8271cnlqpcs5hqg5hr5eqn2" while reading response header from upstream, client: 192.168.1.7, server: www.cidev.com, request: "GET /logout HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "www.cidev.com", referrer: "http://www.cidev.com/accounts"

2011/12/20 21:23:18 [error] 1198#0: *2004 FastCGI sent in stderr: "session destroy: 
session create: eut6sc9sg9pe88l6987uqb5311" while reading response header from upstream, client: 192.168.1.7, server: www.cidev.com, request: "GET /login HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "www.cidev.com", referrer: "http://www.cidev.com/accounts"

2011/12/20 21:23:18 [error] 1198#0: *2004 FastCGI sent in stderr: "session write: eut6sc9sg9pe88l6987uqb5311" while reading upstream, client: 192.168.1.7, server: www.cidev.com, request: "GET /login HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "www.cidev.com", referrer: "http://www.cidev.com/accounts"

**Comment by paulm17** [comment]
Alright, I solved the previous issue.  It now doesn't create another session with the previous id as well as another one.

http://pastie.org/3049457

Dan, hopefully you can take a look and make a better class?

Thanks

**Comment by danmontgomery** [comment]
DB, cookie and cache sessions all use a cookie for tracking... So if there's an issue writing to the cookie it would make sense that these don't work. I haven't tested with 2.1 (or fcgi), so I can't comment on these issues right now, but I'll certainly look into them.

In the mean time, it seems the simple solution would be to disable __destruct() in the session class and use CI's _output() method to write the cookie before output is sent: http://pastie.org/3050571

**Comment by TrejGun** [comment]
i have the same problem and your suggestion works good

**Comment by danmontgomery** [comment]
The headers issue is fixed in the 0.0.7 tag, take a look when you get the chance

**Comment by projenix** [comment]
You may have ran out of disk space.
